# Generated by Django 5.1.1 on 2024-09-13 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_room_connected_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='connected_users',
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.room')),
            ],
            options={
                'unique_together': {('room', 'username')},
            },
        ),
    ]
